name: RunFrameworkTests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore dependencies
      run: dotnet restore Framework
    - name: Build
      run: dotnet build Framework --no-restore
    - name: Test
      run: dotnet test Framework --no-build --verbosity normal
